[package]
name = "schedule-template"
version = "0.1.0"
edition = "2021"

[dependencies]
soph = { version = "0.28.1", default-features = false }
soph-schedule = { version = "0.28.1", default-features = false }
